### ISSUE TITLE
关于打洞后真实IP的问题

### ISSUE THREAD

**Issue by naizhao** [rapiz1/rathole#221] opened 2023-02-16 09:29 UTC
现在通过rathole打洞后，服务所拿到的IP是rathole服务器的IP地址，并不是外部请求发起方的IP地址。frp支持Proxy Protocol来传递真实IP，rathole有这样的计划吗？

**Comment by fernvenue** [comment] 2023-02-16 10:02
Duplicate of https://github.com/rapiz1/rathole/issues/142, but let me give you an example with NGINX, setup an NGINX server on the outside:

```
stream {
    server {
        listen 8080;
        proxy_pass rathole.server:8081;
        proxy_protocol on;
    }
}
```

As you can see, all the requests will be send to our `rathole.server:8081` with Proxy Protocol, and here's our Rathole configurations:

```
[server.services.example]
type = "tcp"
bind_addr = "rathole.server:8081"

[client.services.example]
type = "tcp"
local_addr = "client.nginx:80"
```

Accept the Proxy Protocol on the local NGINX:

```
http {
    #...
    server {
        listen 80   proxy_protocol;
        #...
    }
}
```

All done, that's just an example, you can use any other application you want to setup your own Reverse Proxy with Proxy Protocol and connect them using Rathole. Hope this can help you and other people who also looking for Proxy Protocol, and make sure you have searched other issues and found no duplicates next time :)

**Comment by naizhao** [comment] 2023-02-16 13:22
what I need to achieve is to proxy SMTP protocol and the backend service's postfix. frp can doing this with setting proxy_protocol_version = v2

**Comment by fernvenue** [comment] 2023-02-16 13:34
Again, this is a duplicate issue of https://github.com/rapiz1/rathole/issues/142, as @rapiz1 said, Rathole will handle it but will not to do that by itself:

> rathole doesn't interface with the application layer protocol. - https://github.com/rapiz1/rathole/issues/142

So you can use your own Proxy Protocol service with Rathole, it doesn't matter you wanna proxy SMTP or something, they all based on TCP and UDP, Rathole can handle that.

**Closed** 2023-03-07 12:45 UTC
Labels: enhancement
